In [1]:
# 导入包
import pandas as pd 
import numpy as np

In [2]:
# 读取数据集
ds1 = pd.read_csv('./dataset/01handing_sport_dataset.csv')
ds2 = pd.read_csv('./dataset/02handing_normal_dataset.csv')
ds3 = pd.read_csv('./dataset/03Double lane change_sport_dataset.csv')
ds4 = pd.read_csv('./dataset/04Double lane change_normal_dataset.csv')
ds5 = pd.read_csv('./dataset/05sine-sweep_normal_dataset.csv')
ds6 = pd.read_csv('./dataset/06sine-sweep_sport_dataset.csv')
ds7 = pd.read_csv('./dataset/07sine steer_sport_dataset.csv')
ds8 = pd.read_csv('./dataset/08sine steer_normal_dataset.csv')
ds9 = pd.read_csv('./dataset/09step steer_sport_dataset.csv')
ds10 = pd.read_csv('./dataset/10step steer_normal_dataset.csv')
ds11 = pd.read_csv('./dataset/11steady state corner_sport_dataset.csv')
ds12 = pd.read_csv('./dataset/12steady state corner_normal_dataset.csv')
ds13 = pd.read_csv('./dataset/13Acceleration barking_sport_dataset.csv')
ds14 = pd.read_csv('./dataset/14Acceleration barking_normal_dataset.csv')

In [3]:
ds1.head()

,t,Ax,Ay,Yaw_rate,Vx,Steer,Slip_FL,Slip_FR,Slip_RL,Slip_RR,Beta
0,0.00,0.000000,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000e+00
1,0.02,-0.216631,8.968221e-18,1.538842e-19,95.396155,-9.269872e-18,0.000017,0.000017,-0.000229,-0.000229,-1.187478e-20
2,0.04,-0.216631,8.968221e-18,1.538842e-19,95.396155,-9.269872e-18,0.000017,0.000017,-0.000229,-0.000229,-1.187478e-20
3,0.06,0.242776,-8.776007e-17,-2.296124e-16,95.398216,6.423832e-16,0.002904,0.002904,-0.000288,-0.000288,-8.924312e-19
4,0.08,0.242776,-8.776007e-17,-2.296124e-16,95.398216,6.423832e-16,0.002904,0.002904,-0.000288,-0.000288,-8.924312e-19

In [4]:
print(ds1.shape, ds2.shape, ds3.shape, ds4.shape, ds5.shape, ds6.shape, ds7.shape, ds8.shape, ds9.shape, ds10.shape, ds11.shape, ds12.shape, ds13.shape, ds14.shape)

(1401, 11) (2001, 11) (401, 11) (401, 11) (1501, 11) (1501, 11) (301, 11) (301, 11) (151, 11) (151, 11) (1001, 11) (1501, 11) (201, 11) (201, 11)

## 将各个工况的数据集叠加起来

In [5]:
dataset = pd.concat([ds1, ds2, ds3, ds4, ds5, ds6, ds7, ds8, ds9, ds10, ds11, ds12, ds13, ds14], axis=0, ignore_index=True)

In [6]:
dataset.head()

,t,Ax,Ay,Yaw_rate,Vx,Steer,Slip_FL,Slip_FR,Slip_RL,Slip_RR,Beta
0,0.00,0.000000,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000e+00
1,0.02,-0.216631,8.968221e-18,1.538842e-19,95.396155,-9.269872e-18,0.000017,0.000017,-0.000229,-0.000229,-1.187478e-20
2,0.04,-0.216631,8.968221e-18,1.538842e-19,95.396155,-9.269872e-18,0.000017,0.000017,-0.000229,-0.000229,-1.187478e-20
3,0.06,0.242776,-8.776007e-17,-2.296124e-16,95.398216,6.423832e-16,0.002904,0.002904,-0.000288,-0.000288,-8.924312e-19
4,0.08,0.242776,-8.776007e-17,-2.296124e-16,95.398216,6.423832e-16,0.002904,0.002904,-0.000288,-0.000288,-8.924312e-19

In [7]:
dataset.shape

(11014, 11)

In [8]:
dataset.describe()

,t,Ax,Ay,Yaw_rate,Vx,Steer,Slip_FL,Slip_FR,Slip_RL,Slip_RR,Beta
count,11014.000000,11014.000000,1.101400e+04,1.101400e+04,11014.000000,11014.000000,11014.000000,11014.000000,11014.000000,11014.000000,1.101400e+04
mean,13.025241,-0.019901,2.196932e+00,7.636812e+00,83.855105,49.178442,0.036387,0.009520,-0.003199,-0.001959,2.030482e-01
std,9.891050,1.401415,2.952610e+00,8.962960e+00,37.864399,107.271882,0.220612,0.053421,0.016990,0.008482,8.118070e-01
min,0.000000,-9.097593,-8.143891e+00,-2.243175e+01,0.000000,-89.957700,-0.168328,-0.171409,-0.265443,-0.143988,-3.737598e+00
25%,4.085000,-0.066893,1.108144e-15,4.904504e-15,50.647050,0.000000,0.001349,0.000423,-0.000548,-0.000479,-2.371926e-01
50%,11.320000,0.002694,2.382634e+00,5.222823e+00,79.703573,18.494637,0.001884,0.001398,-0.000331,-0.000334,2.361689e-17
75%,20.600000,0.042886,3.181536e+00,1.392916e+01,97.771517,69.770195,0.011894,0.004013,-0.000248,-0.000248,1.150395e+00
max,40.000000,3.784873,8.247634e+00,2.752401e+01,149.962213,720.000000,2.483597,0.542127,0.005655,0.000000,3.569708e+00

In [9]:
dataset.drop('t', axis=1, inplace=True)

In [10]:
dataset.head()

,Ax,Ay,Yaw_rate,Vx,Steer,Slip_FL,Slip_FR,Slip_RL,Slip_RR,Beta
0,0.000000,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000e+00
1,-0.216631,8.968221e-18,1.538842e-19,95.396155,-9.269872e-18,0.000017,0.000017,-0.000229,-0.000229,-1.187478e-20
2,-0.216631,8.968221e-18,1.538842e-19,95.396155,-9.269872e-18,0.000017,0.000017,-0.000229,-0.000229,-1.187478e-20
3,0.242776,-8.776007e-17,-2.296124e-16,95.398216,6.423832e-16,0.002904,0.002904,-0.000288,-0.000288,-8.924312e-19
4,0.242776,-8.776007e-17,-2.296124e-16,95.398216,6.423832e-16,0.002904,0.002904,-0.000288,-0.000288,-8.924312e-19

In [11]:
dataset.shape

(11014, 10)

In [12]:
dataset.to_csv('./dataset/train_data.csv')